require("dotenv").config();
const mongoose = require("mongoose");
const User = require("../models/UserModel");
const Medication = require("../models/Medication");

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("MongoDB connected...");

    // Clear existing data
    await User.deleteMany({});
    await Medication.deleteMany({});
    console.log("Existing data cleared!");

    // Seed Users
    const users = [
      {
        name: "Admin",
        email: "admin@example.com",
        password: "Admin123!",
        role: "admin",
        store: "Store 1",
      },
      {
        name: "Manager",
        email: "manager@example.com",
        password: "Manager123!",
        role: "inventoryManager",
        store: "Store 1",
      },
      {
        name: "Clerk",
        email: "clerk@example.com",
        password: "Clerk123!",
        role: "clerk",
        store: "Store 1",
      },
    ];

    await User.create(users);
    console.log("Users seeded!");

    // Seed Medications
    const medications = [
      {
        name: "Ibuprofen",
        genericName: "Ibuprofen",
        lot: "BC#2346",
        expirationDate: new Date("2025-06-30"),
        class: "Antiinflammatory",
        store: "Store 1",
        ndcNumber: "12345-1189",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 200,
      },
      {
        name: "Aspirin",
        genericName: "Acetylsalicylic acid",
        lot: "BC#4567",
        expirationDate: new Date("2025-08-15"),
        class: "Analgesic",
        store: "Store 2",
        ndcNumber: "54321-4476",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 150,
      },
      {
        name: "Metformin",
        genericName: "Metformin Hydrochloride",
        lot: "BC#9876",
        expirationDate: new Date("2026-02-28"),
        class: "Antidiabetic",
        store: "Store 1",
        ndcNumber: "23456-7770",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 120,
      },
      {
        name: "Lisinopril",
        genericName: "Lisinopril",
        lot: "BC#1234",
        expirationDate: new Date("2026-01-20"),
        class: "Antihypertensive",
        store: "Store 2",
        ndcNumber: "34567-2224",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 180,
      },
      {
        name: "Amoxicillin",
        genericName: "Amoxicillin",
        lot: "BC#5678",
        expirationDate: new Date("2025-12-25"),
        class: "Antibiotic",
        store: "Store 1",
        ndcNumber: "45678-2675",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 500,
      },
      {
        name: "Cetirizine",
        genericName: "Cetirizine Hydrochloride",
        lot: "BC#4321",
        expirationDate: new Date("2026-07-15"),
        class: "Other",
        store: "Store 2",
        ndcNumber: "87654-3670",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 95,
      },
      {
        name: "Atorvastatin",
        genericName: "Atorvastatin Calcium",
        lot: "BC#2468",
        expirationDate: new Date("2025-11-10"),
        class: "Antihypertensive",
        store: "Store 1",
        ndcNumber: "13579-2278",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 110,
      },
      {
        name: "Omeprazole",
        genericName: "Omeprazole",
        lot: "BC#9753",
        expirationDate: new Date("2025-10-30"),
        class: "Other",
        store: "Store 2",
        ndcNumber: "97531-6280",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 140,
      },
      {
        name: "Simvastatin",
        genericName: "Simvastatin",
        lot: "BC#6482",
        expirationDate: new Date("2026-05-25"),
        class: "Antidiabetic",
        store: "Store 1",
        ndcNumber: "56432-9096",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 160,
      },
      {
        name: "Ciprofloxacin",
        genericName: "Ciprofloxacin",
        lot: "BC#3782",
        expirationDate: new Date("2025-09-18"),
        class: "Antibiotic",
        store: "Store 2",
        ndcNumber: "87654-2370",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 300,
      },
      {
        name: "Naproxen",
        genericName: "Naproxen Sodium",
        lot: "BC#4837",
        expirationDate: new Date("2025-11-01"),
        class: "Antiinflammatory",
        store: "Store 1",
        ndcNumber: "24567-8928",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 220,
      },
      {
        name: "Hydrochlorothiazide",
        genericName: "Hydrochlorothiazide",
        lot: "BC#5913",
        expirationDate: new Date("2025-08-30"),
        class: "Antihypertensive",
        store: "Store 2",
        ndcNumber: "97865-3385",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 130,
      },
      {
        name: "Clindamycin",
        genericName: "Clindamycin Phosphate",
        lot: "BC#6048",
        expirationDate: new Date("2026-06-15"),
        class: "Antibiotic",
        store: "Store 1",
        ndcNumber: "47862-9232",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 250,
      },
      {
        name: "Losartan",
        genericName: "Losartan Potassium",
        lot: "BC#7182",
        expirationDate: new Date("2025-07-20"),
        class: "Antihypertensive",
        store: "Store 2",
        ndcNumber: "56439-0211",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 175,
      },
      {
        name: "Glimepiride",
        genericName: "Glimepiride",
        lot: "BC#8094",
        expirationDate: new Date("2026-01-10"),
        class: "Antidiabetic",
        store: "Store 1",
        ndcNumber: "09876-2132",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 210,
      },
      {
        name: "Tramadol",
        genericName: "Tramadol Hydrochloride",
        lot: "BC#8472",
        expirationDate: new Date("2026-03-05"),
        class: "Analgesic",
        store: "Store 2",
        ndcNumber: "90234-1978",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 95,
      },
      {
        name: "Prednisone",
        genericName: "Prednisone",
        lot: "BC#4629",
        expirationDate: new Date("2025-12-12"),
        class: "Antiinflammatory",
        store: "Store 1",
        ndcNumber: "34567-1187",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 100,
      },
      {
        name: "Levofloxacin",
        genericName: "Levofloxacin",
        lot: "BC#5193",
        expirationDate: new Date("2025-10-08"),
        class: "Antibiotic",
        store: "Store 2",
        ndcNumber: "78543-1978",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 150,
      },
      {
        name: "Glyburide",
        genericName: "Glyburide",
        lot: "BC#6704",
        expirationDate: new Date("2026-02-15"),
        class: "Antidiabetic",
        store: "Store 1",
        ndcNumber: "23456-1890",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 180,
      },
      {
        name: "Ramipril",
        genericName: "Ramipril",
        lot: "BC#9023",
        expirationDate: new Date("2025-11-25"),
        class: "Antihypertensive",
        store: "Store 2",
        ndcNumber: "90123-1767",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 160,
      },
      {
        name: "Fluoxetine",
        genericName: "Fluoxetine",
        lot: "BC#6157",
        expirationDate: new Date("2025-09-30"),
        class: "Other",
        store: "Store 1",
        ndcNumber: "87654-1410",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 90,
      },
      {
        name: "Azithromycin",
        genericName: "Azithromycin",
        lot: "BC#3581",
        expirationDate: new Date("2025-08-20"),
        class: "Antibiotic",
        store: "Store 2",
        ndcNumber: "45321-7765",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 300,
      },
      {
        name: "Duloxetine",
        genericName: "Duloxetine Hydrochloride",
        lot: "BC#7892",
        expirationDate: new Date("2026-04-15"),
        class: "Other",
        store: "Store 1",
        ndcNumber: "65432-7798",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 85,
      },
      {
        name: "Diclofenac",
        genericName: "Diclofenac Sodium",
        lot: "BC#1936",
        expirationDate: new Date("2026-01-18"),
        class: "Antiinflammatory",
        store: "Store 2",
        ndcNumber: "10293-7775",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 130,
      },
      {
        name: "Spironolactone",
        genericName: "Spironolactone",
        lot: "BC#4859",
        expirationDate: new Date("2025-12-22"),
        class: "Antihypertensive",
        store: "Store 1",
        ndcNumber: "45987-3854",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 190,
      },
      {
        name: "Rosuvastatin",
        genericName: "Rosuvastatin Calcium",
        lot: "BC#7641",
        expirationDate: new Date("2026-03-01"),
        class: "Other",
        store: "Store 2",
        ndcNumber: "23456-5391",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 110,
      },
      {
        name: "Meloxicam",
        genericName: "Meloxicam",
        lot: "BC#5823",
        expirationDate: new Date("2026-07-12"),
        class: "Antiinflammatory",
        store: "Store 1",
        ndcNumber: "87654-5486",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 170,
      },
      {
        name: "Hydrocodone",
        genericName: "Hydrocodone Bitartrate",
        lot: "BC#3287",
        expirationDate: new Date("2025-10-30"),
        class: "Analgesic",
        store: "Store 2",
        ndcNumber: "56432-9354",
        createdBy: "SeedUser",
        threshold: 10,
        quantity: 200,
      },
      {
        name: "Carvedilol",
        genericName: "Carvedilol",
        lot: "BC#4072",
        expirationDate: new Date("2025-09-25"),
        class: "Antihypertensive",
        store: "Store 1",
        ndcNumber: "45678-2244",
        createdBy: "SeedUser",
        threshold: 20,
        quantity: 180,
      },
      {
        name: "Metoprolol",
        genericName: "Metoprolol Tartrate",
        lot: "BC#5938",
        expirationDate: new Date("2026-02-05"),
        class: "Antihypertensive",
        store: "Store 2",
        ndcNumber: "13335-1119",
        createdBy: "SeedUser",
        threshold: 30,
        quantity: 140,
      },
    ];

    await Medication.create(medications);
    console.log("Medications seeded!");

    // Close
    mongoose.connection.close();
    console.log("Database seeding completed and connection closed!");
  } catch (error) {
    console.error("Error seeding the database:", error);
    mongoose.connection.close();
    process.exit(1);
  }
};

seedDatabase();
